apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: backend
      jibGradle:
        project: backend
    - image: adminserver
      jibGradle:
        project: adminserver
deploy:
  kubectl:
    manifests:
      - kubernetes/backend-deployment.yaml
      - kubernetes/adminserver-deployment.yaml
