apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: backend
      jibGradle:
        project: backend
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yaml
