apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: backend
      jibGradle:
        project: backend
    - image: admin-server
      jibGradle:
        project: admin-server
deploy:
  kubectl:
    manifests:
      - kubernetes/backend-deployment.yaml
      - kubernetes/admin-server-deployment.yaml
