apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: spring-adminserver
  template:
    metadata:
      labels:
        app: spring-adminserver
    spec:
      containers:
        - name: spring-adminserver-pod
          image: adminserver
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-adminserver-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      nodePort: 32323
  selector:
    app: spring-adminserver
